# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0b77a572e0a9088cba8e0df805a4c06958d79f96601f0c2e625e81b34cfc56f490fd56174067f97f149cc5ea09667f2a8e813a1bd1661e18653f5f52df3beb

test:
  secret_key_base: a6a72f2ed059ee2bd3eed430729f1720f305401cfb5fd99419f7d2c9cb525cf33980924df1ad16ee541655a94ee056f79273d6eef2592d0b9ec8f8beaa2c9c61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
